version: "3"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  myadmin:
    image : phpmyadmin
    container_name: myadmin
    ports:
      - "8082:80"
    environment:
      - PMA_ABSOLUTE_URI=http://myadmin.blc.diverse-team.fr
  back:
    image: back-tlc
    build: ./api
    restart: on-failure
    ports: 
      - "8080:8080"
  front:
    image: front-tlc
    build: ./front
    volumes:
      - ./server-confs:/server-confs
    ports:
      - "80:8080"
      - "443:83"
    environment:
      - SERVER_NAME=blc.diverse-team.fr doodle.blc.diverse-team.fr pad.blc.diverse-team.fr phpmyadmin.blc.diverse-team.fr
      - SERVE_FILES=yes
      - DISABLE_DEFAULT_SERVER=no
      - PROXY_REAL_IP=yes
      #- AUTO_LETS_ENCRYPT=yes
      #- REDIRECT_HTTP_TO_HTTPS=yes
      - USE_LIMIT_REQ=no
      - HTTP2=no
      - FEATURE_POLICY=accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'self'; usb 'none'; vibrate 'none'; vr 'none'

